---
# Ruby LSP Configuration for Music Topos

# Enable all bundled add-ons
enable_all_bundled_add_ons: true

# Configure code completion
code_completion:
  include_gems: false
  snippets: true

# Configure code formatting
formatting:
  rubocop:
    enabled: true

# Configure diagnostics
diagnostics:
  rubocop:
    enabled: true
  ruby:
    enabled: true

# Configure hover information
hover:
  enabled: true

# Configure definition search
definition:
  enabled: true

# Configure references
references:
  enabled: true

# Configure rename
rename:
  enabled: true

# Configure semantic tokens (syntax highlighting)
semantic_tokens:
  enabled: true
